### ISSUE TITLE
Add support for files oder suno.ai

### ISSUE THREAD

**Issue by DerP4si** [solaluset/DandelionMusic#125]
Hey,
Thx for your work!
Is there a way to play files?
Is there a way how direct streams from suno.ai could be possible?

**Comment by solaluset** [comment]
It's not supported by `yt-dlp` and doesn't have an API (yet?). I don't think it's possible.
Still, I can look into it if you share some examples of links you want to be supported.

**Comment by DerP4si** [comment]
This is an example song...
https://app.suno.ai/song/212909aa-61e9-4b50-b707-898cced7d341

Or could it be possible to simply upload a file to discord and then link the uploaded file to the bot ?

**Comment by solaluset** [comment]
Yes, you can give the bot Discord message link or attachment link to play.
Looks like I figured out how to play directly from Suno though, I can implement it if needed.

**Comment by DerP4si** [comment]
wow that would be awesome!

**Comment by solaluset** [comment]
Not sure how to do it with music, with videos you just choose "share" (mobile version) and copy link or right click and copy link (desktop version).
If the bot has access to a message, I suggest copying link to the message instead and it'll grab the attachments automatically.

**Comment by DerP4si** [comment]
hmmm that doesnt work...
![image](https://github.com/solaluset/DandelionMusic/assets/28807283/cc3c114f-3561-454b-8798-71386a4aab23)

**Comment by solaluset** [comment]
Are you using the latest version?

**Comment by DerP4si** [comment]
oh uff i didnt adjust the docker compose after you changed your profilename, so it didn't updateted in a while... ^^ But now i have and yes indeed... At least the fileplaying works as intended... thx! But i think a suno support would be cool anyhow.

**Comment by solaluset** [comment]
Can you please check if the above works for you?

**Comment by DerP4si** [comment]
works! Amazing, thx!
