### ISSUE TITLE
Opus

### ISSUE THREAD

**Issue by kaanalp28** [solaluset/DandelionMusic#129]
Guys this is not really an issue with the bot but rather about me. I'm trying to change the host service these days and im currently trying a nix based service. I added pkgs.ffmpeg in the packages list in the nix.dev file, and it worked just fine, so i did the same thing for opus and added pkgs.libopus as well, but for some reason it kept saying opus was not found, even though ffmpeg was found when installed in the same file. am i missing something here? ty, sorry for the lack of detail the server crashed and i cant rlly provide the error details until its back up i will try to when it is tho ty.

**Comment by solaluset** [comment]
I don't have experience with NixOS, but looks like `ctypes` can't find the library automatically. Here's how `discord.py` is patched to work properly:
https://github.com/NixOS/nixpkgs/blob/c19daec1e8386996caf0d2b442871373816c332a/pkgs/development/python-modules/discordpy/default.nix#L37
Maybe you can make it run by figuring out the path and adding the directory to the `LD_LIBRARY_PATH` env var. Or adding `opus.load_opus(file_path)` before the check.
