### ISSUE TITLE
Add latest tag in docker hub

### ISSUE THREAD

**Issue by Rilith** [solaluset/DandelionMusic#136]
Can you please add the :latest tag in docker? Thak you! (i'm using casaOS but for a bug in the last release i can only pull with the tag "latest". Thank you!

**Comment by solaluset** [comment]
Can you provide more information about the bug? I don't want to add another tag unless there's no other solution.

**Comment by Rilith** [comment]
yeah, maybe you are right, the bug was solved one week ago, i guess i should just wait for the new version)

https://github.com/IceWhaleTech/CasaOS/issues/1753

**Comment by solaluset** [comment]
I see, that's great. I can temporarily create the tag if you want.

**Comment by Rilith** [comment]
if you can it would be great! Also i do not now anything about docker conventions with tag but i see that a lot of projects have the latest tag!

**Comment by solaluset** [comment]
Done!

> a lot of projects have the latest tag

This project already has `master` that holds latest version, and I don't want to have two identical tags. I'll keep the `latest` tag until the issue is resolved.

**Comment by Rilith** [comment]
Thank you!

**Comment by solaluset** [comment]
Can you confirm that this issue was resolved? I'm a little confused because the next version was already released but the original issue is not marked as closed.

**Comment by Rilith** [comment]
Hi! Sorry for the delay!

Yeah it works now, i just checked! Thank you again!
