### ISSUE TITLE
Spotify song/playlist error

### ISSUE THREAD

**Issue by dpyh121** [solaluset/DandelionMusic#170]
I already set my tokens but when i try to open song with spotify link.
Bot responds "Command raised an exception: ClientConnectorCertificateError: Cannot connect to host open.spotify.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]"

How can i fix this issue?

Youtube works btw.

**Comment by dpyh121** [comment]
![screenshot](https://github.com/user-attachments/assets/4bf92368-890b-4810-bcf9-7a439f6b6a05)

**Comment by solaluset** [comment]
This is most likely an issue with your system. Which OS do you use?

**Comment by solaluset** [comment]
If you're using Spotify API, try without it. If that still doesn't work, I'll try to mitigate this issue by disabling the validation.

**Comment by solaluset** [comment]
You can also try:
```bash
pip install pip_system_certs
```
And
```bash
pip install python-certifi-win32
```
