### ISSUE TITLE
Bad sound quality

### ISSUE THREAD

**Issue by StonebanksYT** [solaluset/DandelionMusic#63]
The sound quality is very poor now. Any fixes? The audio is distorted and not stereo at all.

**Comment by Krutyi-4el** [comment]
Please share the link which causes this. Also check the settings of your voice channel, you may need to set bigger bitrate.

(does discord support stereo at all?)

**Comment by StonebanksYT** [comment]
Every song is distorted and unclear now. It's not the bitrate I've checked. Yeah it does support stereo and in earlier versions the quality was clear and much better than current audio quality.

**Comment by Krutyi-4el** [comment]
The hosting doesn't matter that much, but if it uses shared IPs YouTube may restrict access to good quality. The part of the bot which does sound processing wasn't changed in recent updates (you can check with earlier versions, results should be the same), so it should be an external problem.
Try to run it on different machine and let me know if that helps.

**Comment by TransitNode** [comment]
I have the exact same issue, sound quality is very bad no matter the audio source, discord channel bitrate. 

I speculate the PCM audio format might cause performance issues, maybe a switch to FFmpegOpusAudio would be of benefit. PCM is already encoding to the Opus format anyway and using the FFmpegOpusAudio would produce Opus packets directly. 

https://discordpy.readthedocs.io/en/stable/api.html#ffmpegopusaudio

**Comment by Krutyi-4el** [comment]
Converting to PCM surely introduces some overhead, but:
- If it was a performance issue, the audio would still be good but it'd be often interrupted
- PCM allows us to easily control the volume
- There is a chance that user's FFmpeg doesn't support opus as output

I still think that this issue is caused by YouTube. To help me identify it you can:
- Try running the bot with another IP and on another device
- Try running yt-dlp to download the video and `yt-dlp -x` to extract the audio and see if it results in a good quality
- Try running FFmpeg on another input (any audio file) to see if it's recoding it properly
- Send here your OS, FFmpeg version (or even provide a source you've got it from) and the song link which gives poor audio

**Comment by StonebanksYT** [comment]
the bot is not working at all now. Error 403 or sm

**Comment by Krutyi-4el** [comment]
> the bot is not working at all now. Error 403 or sm

403 means forbidden. YouTube is restricting you.

I've published a new release with updated requirements, it *may* solve this issue. Try it out. If it doesn't help, please share info described above.

**Comment by StonebanksYT** [comment]
> > the bot is not working at all now. Error 403 or sm
> 
> 403 means forbidden. YouTube is restricting you.
> 
> I've published a new release with updated requirements, it _may_ solve this issue. Try it out. If it doesn't help, please share info described above.

Yea uploaded the new version..the bot is working but the sound quality is like the previous version..volume is fluctuating and song is not clear..dont even know if its just me or what

**Comment by Krutyi-4el** [comment]
How are you listening to it, btw? Do you use a phone or PC, speakers or headphones?

**Comment by StonebanksYT** [comment]
> How are you listening to it, btw? Do you use a phone or PC, speakers or headphones?

I have stereo headphones and the bot's sound quality was fine a month ago I guess, that's when the hosting website changed their node to a new big node with dynamic IP but I'm sure the sound quality dropped after I switched to the new node of my hosting website. You earlier mentioned that if it uses shared ip then YouTube may cause issues. Can that be a problem? I will debug this using local hosting and then check the quality and I'll comment later

**Comment by RevMirin** [comment]
Bluetooth headphones ruin sound

**Comment by solaluset** [comment]
@StonebanksYT is there any new info on this?

**Comment by StonebanksYT** [comment]
The sound quality is fine now I just checked. Closing this issue
